# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190430_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(default='5'),
        ),
    ]
