# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_post', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('completed', models.IntegerField(default='0')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('credits', models.IntegerField(default='0')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
