# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190430_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='date_post',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
